language: go

go_import_path: github.com/romainmenke/travis-env-test

go:
- 1.5.4
- 1.6.4
- 1.7.4
- master

script:
- go test .

notifications:
  webhooks: https://httpmiddlewarevet.herokuapp.com/webhook/travis
