language: go

go_import_path: github.com/romainmenke/travis-env-test

go:
- 1.5.x
- 1.6.x
- 1.7.x
- master

# script:
# - go test .
# - echo $TRAVIS_GO_VERSION
# - echo $TRAVIS_COMMIT
# - "curl -X GET 'https://httpmiddlewarevet.herokuapp.com/webhook/travis?commit=$TRAVIS_COMMIT&version=$TRAVIS_GO_VERSION'"

after_script:
- echo $TRAVIS_GO_VERSION
- echo $TRAVIS_COMMIT
- "curl -X GET https://httpmiddlewarevet.herokuapp.com/webhook/travis?commit=$TRAVIS_COMMIT&version=$TRAVIS_GO_VERSION"
