language: go

go_import_path: github.com/romainmenke/travis-env-test

go:
- 1.5.x
- 1.6.x
- 1.7.x
- master

matrix:
  before_script:
    - echo https://httpmiddlewarevet.herokuapp.com/webhook/travis/$TRAVIS_GO_VERSION
    - export WEBHOOK_URL=https://httpmiddlewarevet.herokuapp.com/webhook/travis/$TRAVIS_GO_VERSION
    - echo $WEBHOOK_URL
  notifications:
    webhooks: ${WEBHOOK_URL}

script:
- go test .
