language: go

go_import_path: github.com/romainmenke/travis-env-test

go:
- 1.5.x
- 1.6.x
- 1.7.x
- master

script:
- go test .

after_script:
- "curl --data \"commit=$TRAVIS_COMMIT&version=$TRAVIS_GO_VERSION\" https://httpmiddlewarevet.herokuapp.com/webhook/travis"
